### ISSUE TITLE
underscore(_) present when on the receive page

### ISSUE THREAD

**Issue by Astro92** [asoltys/coinos#12]
When you load your wallet, then move to the receive page a (_) is always present when you try to input an amount.

Love this project by the way!

**Comment by asoltys** [comment]
Hey, thanks! The underscore was intentional to indicate a blank or zero value but I can see how it might be confusing/annoying, I'll take it out soon

**Comment by asoltys** [comment]
I made it a placeholder for the input so it's not actually a character in the field anymore but is still visible if the field is empty.
