### ISSUE TITLE
Fee estimation on bitcoin mainnet

### ISSUE THREAD

**Issue by spotty-banana** [asoltys/coinos#18]
Hi, first have to say that I'm very happy for this project. I have been looking for simple wallet where I can send and receive BTC, LN and Liquid BTC payments from the same balance.

However, for BTC mainnet the fee selection could be better. Something like high priority - medium - low priority, similarly to electrum for example. Currently the fee is capped at 50 satoshis per byte and for example this week it meant that the tx will be staying in the mempool for long time.

**Comment by asoltys** [comment]
Hi, thanks for the kinds words and I agree with your point. I'll add some user-friendly presets eventually but for now I've gone ahead and just increased the max fee rate to 1000 sats/byte, hopefully that's adequate for the time being.

**Comment by spotty-banana** [comment]
That's a great quickfix, thanks!
